---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Stat forgejo binary
      ansible.builtin.stat:
        path: "{{ forgejo_install_path | default('/usr/local/bin') }}/forgejo"
      register: forgejo_present
    - name: Check forgejo is present
      ansible.builtin.assert:
        that:
          - forgejo_present.stat.exists
        fail_msg: "forgejo not setup"
        success_msg: "forgejo is setup"
